spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/movies
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
  mail:
    host: smtp.gmail.com
    port: 587
    username: "your_email"
    password: "your_code"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  main:
    allow-bean-definition-overriding: true

project:
  poster: ./media/posters
  video: ./media/videos
  trailer: ./media/trailers

base:
  url: "http://localhost:8080"
